# -*- coding: utf-8 -*-
"""123120079_Bintang Putra Permana_Challenge Modul 14

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TFAtU2mcl0rFyuzmYn6C62owVJuiRk3a
"""

import streamlit as st
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from scipy.interpolate import griddata, NearestNDInterpolator
from scipy.ndimage import uniform_filter

# KONFIGURASI HALAMAN
st.set_page_config(
    page_title="Analisis Data Magnetik 2D",
    layout="wide"
)

st.title("🧲 Pengolahan Data Magnetik 2D (Week 14)")
st.markdown("""
Aplikasi ini digunakan untuk:
- Gridding data magnetik
- Visualisasi peta magnetik
- Pemisahan anomali **Regional** dan **Residual**
""")

# SIDEBAR – INPUT DATA
st.sidebar.header("Input Data")

uploaded_file = st.sidebar.file_uploader(
    "Upload data magnetik (.csv)",
    type=["csv"]
)

# FUNGSI DATA DUMMY
def get_dummy_dataframe(grid_size=50):
    x = np.linspace(0, 1000, grid_size)
    y = np.linspace(0, 1000, grid_size)
    X, Y = np.meshgrid(x, y)

    regional = 0.05 * X + 0.02 * Y + 45000
    r = np.sqrt((X - 500)**2 + (Y - 500)**2 + 50**2)
    residual = 5000 * (50 / r)**3
    noise = np.random.normal(0, 1, X.shape)

    total = regional + residual + noise

    df = pd.DataFrame({
        "x": X.flatten(),
        "y": Y.flatten(),
        "t_obs": total.flatten()
    })

    return df.sample(frac=0.8).reset_index(drop=True)

# BACA DATA
if uploaded_file:
    df_input = pd.read_csv(uploaded_file)
else:
    st.warning("Tidak ada data diupload → menggunakan data dummy")
    df_input = get_dummy_dataframe()

st.success(f"Jumlah data: {len(df_input)} titik")

# PARAMETER GRIDDING
st.sidebar.header("Parameter Gridding")

x_min, x_max = df_input['x'].min(), df_input['x'].max()
y_min, y_max = df_input['y'].min(), df_input['y'].max()

cell_size = st.sidebar.number_input(
    "Ukuran Sel (m)",
    min_value=1.0,
    value=(x_max - x_min) / 50
)

interp_method = st.sidebar.selectbox(
    "Metode Interpolasi",
    ["linear", "cubic", "nearest"]
)

# GRIDDATA
xi = np.arange(x_min, x_max + cell_size, cell_size)
yi = np.arange(y_min, y_max + cell_size, cell_size)
X, Y = np.meshgrid(xi, yi)

with st.spinner("Interpolasi data..."):
    T_obs = griddata(
        (df_input['x'], df_input['y']),
        df_input['t_obs'],
        (X, Y),
        method=interp_method
    )

# SIDEBAR – VISUAL SETTING (CHALLENGE)
st.sidebar.header("Visualisasi")

cmap_choice = st.sidebar.selectbox(
    "Colormap",
    ["jet", "viridis", "plasma", "inferno", "seismic"]
)

scale_mode = st.sidebar.radio(
    "Skala Warna",
    ["Auto", "Manual"]
)

if scale_mode == "Manual":
    vmin = st.sidebar.slider("vmin", float(np.nanmin(T_obs)), float(np.nanmax(T_obs)), float(np.nanmin(T_obs)))
    vmax = st.sidebar.slider("vmax", float(np.nanmin(T_obs)), float(np.nanmax(T_obs)), float(np.nanmax(T_obs)))
else:
    vmin, vmax = None, None

# VISUALISASI DATA
st.subheader("1. Visualisasi Data Magnetik")

tab1, tab2 = st.tabs(["Peta Kontur", "Sebaran Titik"])

with tab1:
    fig, ax = plt.subplots(figsize=(9, 6))
    c = ax.contourf(X, Y, T_obs, 25, cmap=cmap_choice, vmin=vmin, vmax=vmax)
    ax.scatter(df_input['x'], df_input['y'], s=5, c='k', alpha=0.3)
    ax.set_aspect('equal')
    ax.set_title("Total Magnetic Intensity")
    fig.colorbar(c, ax=ax, label="nT")
    st.pyplot(fig)

    if st.button("💾 Simpan Peta Kontur"):
        fig.savefig("peta_magnetik.png", dpi=300)
        st.success("Peta disimpan sebagai peta_magnetik.png")

with tab2:
    fig2, ax2 = plt.subplots(figsize=(7, 6))
    sc = ax2.scatter(
        df_input['x'],
        df_input['y'],
        c=df_input['t_obs'],
        cmap=cmap_choice
    )
    fig2.colorbar(sc, ax=ax2, label="nT")
    ax2.set_title("Sebaran Titik Pengukuran")
    st.pyplot(fig2)

# PEMISAHAN REGIONAL – RESIDUAL
st.subheader("2. Pemisahan Regional – Residual")

method = st.selectbox(
    "Metode Pemisahan",
    ["Moving Average 2D", "Trend Surface (Polinomial)"]
)

# Isi NaN
mask_nan = np.isnan(T_obs)
if np.any(mask_nan):
    interp_nn = NearestNDInterpolator(
        list(zip(X[~mask_nan], Y[~mask_nan])),
        T_obs[~mask_nan]
    )
    T_filled = interp_nn(X, Y)
else:
    T_filled = T_obs

if method == "Moving Average 2D":
    window = st.slider("Lebar Window (grid)", 3, 101, 9, step=2)
    Regional = uniform_filter(T_filled, size=window)
else:
    order = st.radio("Orde Polinomial", [1, 2])

    def polyfit2d(x, y, z, order):
        mask = ~np.isnan(z)
        x, y, z = x[mask], y[mask], z[mask]

        if order == 1:
            A = np.c_[np.ones(x.size), x, y]
        else:
            A = np.c_[np.ones(x.size), x, y, x**2, x*y, y**2]

        C, *_ = np.linalg.lstsq(A, z, rcond=None)

        if order == 1:
            return C[0] + C[1]*X + C[2]*Y
        else:
            return C[0] + C[1]*X + C[2]*Y + C[3]*X**2 + C[4]*X*Y + C[5]*Y**2

    Regional = polyfit2d(X, Y, T_obs, order)

Residual = T_obs - Regional

# HASIL
col1, col2 = st.columns(2)

with col1:
    st.markdown("### Regional")
    fig_r, ax_r = plt.subplots(figsize=(6, 5))
    cr = ax_r.contourf(X, Y, Regional, 20, cmap=cmap_choice)
    fig_r.colorbar(cr, ax=ax_r)
    st.pyplot(fig_r)

with col2:
    st.markdown("### Residual")
    fig_res, ax_res = plt.subplots(figsize=(6, 5))
    limit = np.nanpercentile(np.abs(Residual), 98)
    crr = ax_res.contourf(
        X, Y, Residual, 20,
        cmap="seismic",
        vmin=-limit, vmax=limit
    )
    fig_res.colorbar(crr, ax=ax_res)
    st.pyplot(fig_res)